export const BASE_URL = "https://api.themoviedb.org/3/movie";
export const Authorization = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5Y2Y1NjlkZWI3Yzg3ZDBmZTVkZGMxMzBlNWI2ZjdkMCIsInN1YiI6IjY1NWM1ZTg1ZDRmZTA0MDExYjk0NmNmYiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.xOzspNnAcx5TxtEKtdvTC2WKsGEY0bx8aZmmjurEh_U';
